version: '3.7'

volumes:
  logs-nginx:
    name: logs-nginx-${ENV?}
    driver: ${VOLUMES_DRIVER?}
  logs-app:
    name: logs-app-${ENV?}
    driver: ${VOLUMES_DRIVER?}
  logs-supervisor:
    name: logs-supervisor-${ENV?}
    driver: ${VOLUMES_DRIVER?}
  logs-php-fpm:
    name: logs-php-fpm-${ENV?}
    driver: ${VOLUMES_DRIVER?}

services:
  php-fpm:
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
      - logs-app:/var/log/app
      - logs-php-fpm:/var/log/php-fpm
    # cap_add and security_opt are required to enable strace
    # @see https://stackoverflow.com/a/46676868
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - network

  php-worker:
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
      - logs-app:/var/log/app
      - logs-supervisor:/var/log/supervisor
    # cap_add and security_opt are required to enable strace
    # @see https://stackoverflow.com/a/46676868
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - network
    depends_on:
      - php-fpm    

  nginx:
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
      - "${NGINX_HOST_HTTPS_PORT:-443}:443"
    networks:
      network:
        aliases:
          - ${APP_HOST?}
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
      - logs-nginx:/var/log/nginx
    depends_on:
      - redis

  application:
    build:
      args:
        - APP_SSH_PASSWORD=${APP_SSH_PASSWORD?}    
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    # cap_add and security_opt are required to enable strace
    # @see https://stackoverflow.com/a/46676868
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
      - logs-app:/var/log/app
    ports:
      - "${APPLICATION_SSH_HOST_PORT:-2222}:22"
    extra_hosts:
      - host.docker.internal:host-gateway
   
  mysql:
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
    volumes:
      - mysql:/var/lib/mysql
  
  redis:
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    volumes:
      - redis:/data

  logger:
    volumes:
      - logs-nginx:/var/log/nginx
      - logs-app:/var/log/app
      - logs-supervisor:/var/log/supervisor
      - logs-php-fpm:/var/log/php-fpm
